name: Build test with Gradle

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current repository # gitactiond에서 checkout이란 약간 다름: 깃헙 리모트에 올라간 코드를 ci 서버에 내려받은 후 특정 브랜치로 이동하는 작업까지를 말함
        uses: actions/checkout@v4

      - name: Setup JDK Corretto using cached gradle dependencies
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: Build and test with gradle
        run: |
          ./gradlew test
# build 안에 test, bootjar 생성이 나눠져있는데 우리는 굳이 ci에서 bootjar 만들필요가 없어서 안했다고 했다.
#      - name: Publish test results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          files: |
#            ./build/test-results/**/*.xml
