name: Build test with Gradle

on:
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to current repository
        uses: actions/checkout@v4

      - name: Setup JDK Corretto using cached gradle dependencies
        uses: actions/setup-java@v4
        with:
         distribution: 'corretto'
         java-version: 17
         cache: 'gradle'

      - name: Build and test with gradle
        run: ./gradlew test
